language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - export DJANGO_DEBUG=True
  - export DJANGO_TEMPLATE_DEBUG=True
  - export BASE_URL=http://localhost:5000/
  - export DJANGO_SECRET_KEY=shh!1234
  - export DATABASE_URL=postgres://localhost/fobal
  - export DJANGO_EMAIL_HOST=smtp.gmail.com
  - export DJANGO_EMAIL_HOST_USER=futbol5.dev
  - export DJANGO_EMAIL_HOST_PASSWORD=Fu7b0l5_D3V
script: python manage.py test
